TAVILY_API_KEY = "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"

[theme]
base="light"
primaryColor="#a8a69a"

[azure]
account_name = "reactflow"
container_name = "vectorstore"
sas_token = "sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2024-12-13T19:14:40Z&st=2024-12-09T11:14:40Z&spr=https&sig=FOVzT4AOnQMtTzDLqE7SjIJzsn0ICgF6Ctau6cReLJ0%3D"