TAVILY_API_KEY = "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"

LANGCHAIN_API_KEY = "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"

[theme]
base="light"
primaryColor="#a8a69a"

[azure]
account_name = "reactflow"
container_name = "vectorstore"
sas_token = "?sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2024-12-06T16:14:09Z&st=2024-12-06T08:14:09Z&spr=https&sig=S2LbzUau%2BWb18CU99ROVbpEwFymHeou0N4SieOWix2c%3D"